#!/usr/bin/env node
/**
 * Interactive onboarding. Asks for the credentials and campaign defaults a new
 * user needs, then writes .env and data/campaign.json. Safe to re-run: existing
 * values are shown as defaults and kept if you press Enter.
 */
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, '.env');
const CAMPAIGN_PATH = path.join(__dirname, 'data', 'campaign.json');

const c = {
  b: (s) => `\x1b[1m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
};

/** Parse an existing .env into a plain object so re-runs keep current values. */
function readEnv() {
  if (!fs.existsSync(ENV_PATH)) return {};
  return Object.fromEntries(
    fs
      .readFileSync(ENV_PATH, 'utf8')
      .split('\n')
      .filter((l) => l.trim() && !l.trim().startsWith('#') && l.includes('='))
      .map((l) => {
        const i = l.indexOf('=');
        return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
      })
  );
}

const DEFAULT_SUBJECT = 'Quick question';

const DEFAULT_BODY = `Hi {{first_name}},

{{personalized_line}}

I help businesses like {{company}} turn more of their existing leads into booked calls.

Would you be open to a short intro chat this week?

Best,
Your Name`;

async function main() {
  const rl = readline.createInterface({ input: stdin, output: stdout });
  const cur = readEnv();

  const ask = async (label, key, { fallback = '', hint = '', secret = false } = {}) => {
    const existing = cur[key] || fallback;
    const shown = secret && existing ? '••••••••' : existing;
    if (hint) console.log(c.dim('   ' + hint));
    const a = (await rl.question(`   ${label}${shown ? c.dim(` [${shown}]`) : ''}: `)).trim();
    console.log('');
    return a || existing;
  };

  console.log(`
${c.b(c.cyan('  LeadFlow AI — setup'))}
${c.dim('  Scrape leads → personalize with AI → send a throttled cold-email drip')}
${c.dim('  Press Enter to accept the value in brackets. Nothing leaves your machine.')}
`);

  console.log(c.b('  1/4  Apify — lead scraping'));
  const APIFY_TOKEN = await ask('API token', 'APIFY_TOKEN', {
    hint: 'Free account → https://console.apify.com/settings/integrations',
    secret: true,
  });

  console.log(c.b('  2/4  Groq — AI personalization'));
  const GROQ_API_KEY = await ask('API key', 'GROQ_API_KEY', {
    hint: 'Free key → https://console.groq.com/keys',
    secret: true,
  });

  console.log(c.b('  3/4  Gmail — sending'));
  console.log(c.dim('   Needs 2-Step Verification ON, then create an App Password:'));
  console.log(c.dim('   https://myaccount.google.com/apppasswords'));
  const GMAIL_USER = await ask('Your Gmail address', 'GMAIL_USER');
  const GMAIL_APP_PASSWORD = await ask('App Password (16 chars)', 'GMAIL_APP_PASSWORD', {
    secret: true,
  });

  console.log(c.b('  4/4  Your campaign'));
  const fromName = await ask('Sender name (shown to recipients)', '__fromName', {
    fallback: '',
    hint: 'e.g. how you sign your emails',
  });
  const subject = await ask('Default subject line', '__subject', { fallback: DEFAULT_SUBJECT });

  console.log(c.dim('   Default email body — press Enter to use the built-in template.'));
  console.log(c.dim('   You can always edit it later in the dashboard.'));
  const useTemplate = (await rl.question('   Use built-in template? (Y/n): ')).trim().toLowerCase();
  let body = DEFAULT_BODY;
  if (useTemplate === 'n') {
    console.log(c.dim('\n   Type/paste your body. Finish with a line containing only: END\n'));
    const lines = [];
    for (;;) {
      const line = await rl.question('');
      if (line.trim() === 'END') break;
      lines.push(line);
    }
    if (lines.length) body = lines.join('\n');
  }
  console.log('');

  const gap = await ask('Minutes between each email', '__gap', { fallback: '3' });
  const minGap = Math.max(1, Number(gap) || 3) * 60;
  const maxGap = minGap + 60;

  rl.close();

  const env = `# Generated by \`npm run setup\` — this file is gitignored, keep it private.

APIFY_TOKEN=${APIFY_TOKEN}
GOOGLE_MAPS_ACTOR=${cur.GOOGLE_MAPS_ACTOR || 'compass/crawler-google-places'}
APOLLO_ACTOR=${cur.APOLLO_ACTOR || 'code_crafter/apollo-io-scraper'}

GROQ_API_KEY=${GROQ_API_KEY}
GROQ_MODEL=${cur.GROQ_MODEL || 'llama-3.3-70b-versatile'}

GMAIL_USER=${GMAIL_USER}
GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
SMTP_TLS_INSECURE=${cur.SMTP_TLS_INSECURE || 'false'}

MIN_GAP_SECONDS=${minGap}
MAX_GAP_SECONDS=${maxGap}

PORT=${cur.PORT || '3000'}
`;
  fs.writeFileSync(ENV_PATH, env);

  fs.mkdirSync(path.dirname(CAMPAIGN_PATH), { recursive: true });
  fs.writeFileSync(CAMPAIGN_PATH, JSON.stringify({ fromName, subject, body }, null, 2));

  const missing = [
    !APIFY_TOKEN && 'APIFY_TOKEN',
    !GROQ_API_KEY && 'GROQ_API_KEY',
    !GMAIL_USER && 'GMAIL_USER',
    !GMAIL_APP_PASSWORD && 'GMAIL_APP_PASSWORD',
  ].filter(Boolean);

  console.log(c.green('  ✓ Saved .env and data/campaign.json\n'));
  if (missing.length) {
    console.log(c.yellow(`  ⚠ Still blank: ${missing.join(', ')}`));
    console.log(c.dim('    Re-run `npm run setup` once you have them.\n'));
  }
  console.log(`  Start the dashboard:  ${c.b('npm start')}`);
  console.log(c.dim('  Then open http://localhost:' + (cur.PORT || '3000') + '\n'));
}

main().catch((e) => {
  console.error('\nSetup failed:', e.message);
  process.exit(1);
});
